package com.github.shoothzj.agent;

import com.github.shoothzj.agent.constant.PulsarConst;
import net.bytebuddy.agent.builder.AgentBuilder;
import net.bytebuddy.matcher.ElementMatchers;

import java.lang.instrument.Instrumentation;

public class Agent {

    public static void premain(String agentArgs, Instrumentation inst) {
        System.out.println("premain() was called.");
        new AgentBuilder.Default()
                .ignore(ElementMatchers.nameStartsWith("net.bytebuddy.")
                        .or(ElementMatchers.nameStartsWith("org.slf4j.")
                                .or(ElementMatchers.nameStartsWith("org.apache.logging.")
                                        .or(ElementMatchers.nameStartsWith("org.groovy."))
                                        .or(ElementMatchers.nameStartsWith("javassist"))
                                        .or(ElementMatchers.nameStartsWith(".asm."))
                                        .or(ElementMatchers.nameStartsWith("sun.reflect"))
                                        // that's generated by compiler, ignore
                                        .or(ElementMatchers.isSynthetic()))))
                .type(ElementMatchers.named(PulsarConst.CLASS_PERSISTENT_TOPIC))
                .transform(new AgentTransformer())
                .with(AgentBuilder.RedefinitionStrategy.RETRANSFORMATION)
                .with(new AgentListener())
                .installOn(inst);
        System.out.println("premain() ended.");
    }

}
